services:

  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "3307:3306"
      - "2222:22"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "./custom:/var/www/html/custom"
      - "./files:/var/www/html/files"
      - "./public/media:/var/www/html/public/media"
      - "./theme:/var/www/html/theme"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=1
      - PHP_VERSION=8.3
      - SHOPWARE_MEMORY_LIMIT=2G

  database:
    image: mariadb:11.4
    container_name: shopware-database
    environment:
      MARIADB_DATABASE: shopware
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: shopware
      MARIADB_PASSWORD: shopware
    volumes:
      - db-data:/var/lib/mysql:rw
    healthcheck:
      test: [ "CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-proot" ]
      start_period: 10s
      start_interval: 3s
      interval: 5s
      timeout: 1s
      retries: 10
    networks:
      - web

volumes:
  db-data:

networks:
  web:
    external: false